### ISSUE TITLE
callDidDisconnect: called right after callDidConnect: without any errors. Cannot make an outbound call.

### ISSUE THREAD

**Issue by nicolettemanas** [twilio/voice-callkit-quickstart-objc#6]
Hi team,

I am using TwilioVoiceClient 2.0.0-beta6.
I am trying to make a call between two ios devices using the voice-quickstart-server-python project you provided.

I followed the steps in your quickstart guide but changed the TwiML app Voice request URL from https://xxx.ngrok.io/outgoing to https://xxx.ngrok.io/placeCall.

Please refer to the ff steps: 

1. Change IDENTITY field in generating the AccessToken under server.py to 'voice_test'
```
token = AccessToken(account_sid, api_key, api_key_secret,'voice_test')
```
2. Run the server and build the app to ios device 1 (receiver)
3. Device 1 to request accessToken and register it for voip push notifications via the VoiceClient sharedInstance. Registration is successful.
4. Change IDENTITY field in generating the AccessToken under server.py to 'quick_start'
```
token = AccessToken(account_sid, api_key, api_key_secret,'quick_start')
```
5. Change client.calls.create() parameters under server.py to
```
call = client.calls.create(url=request.url_root + 'incoming', to='client:' + 'voice_test', from_='client:' + 'quick_start')
```
to imitiate a call from quick_start to voice_test
6. Restart the server and build the app to ios device 2 (caller)
7. Device 2 to request accessToken and register it for voip push notifications via the VoiceClient sharedInstance. Registration is successful.
8. Make a call using Device 2
9.  `callDidConnect:(TVOCall *)call` delegate method is called in Device 2
10. `callDidDisconnect:(TVOCall *)call` delegate method is called in Device 2
11. Device 1 receives the callInvite push notification
12. Device 1 call invite only terminates after timeout 

The `callDidDisconnect:(TVOCall *)call` method is called almost the same time as the Device 1 receives the callInvite notification. 

If the receiver accepts the callInvite, Twilio plays "Congratulations! You have received your first inbound call! Good bye.".

There are no Error logs in Twilio or Xcode consoles.
iOS Devices used are iPhone 6s and iPhone 5 both running on iOS10.1.1.

**Comment by bchen-twilio** [comment]
Hi @nicolettemanas 

Bobie here from the SDK team and I would like to first thank you for the detailed steps and info.
You are actually doing everything right - the original `/placeCall` will indeed call out to another client specified in the `to` parameter and once the call is accepted by the callee and connected, the `url` parameter will trigger another TwiML request, which will hit the `/incomingCall` endpoint. This is why your callee is hearing that congratulatory line.

To make a call between your mobile clients (well you actually almost did), could you try replacing the lines in the `/placeCall` endpoint with:
```
    resp = twiml.Response()
    resp.dial(callerId='quick_start').client('voice_test')
    return resp
```

Once this is working, you can further utilize the python server endpoint by extracting the HTTP request parameters like this:
```
def placeCall():
    resp = twiml.Response()
    toClient = request.values.get('FROM_APP_TO', '')
    if toClient[0] in "+1234567890":
        resp.dial(callerId='CALLER_ID).number(toClient)
    elif len(toClient) > 0:
        resp.dial(callerId='CALLER_ID').client(toClient)

    return resp
```

In your iOS app, you can add this `FROM_APP_TO` into the call parameter dictionary:
```
    [[VoiceClient sharedInstance] call:self.accessToken
                                params:@{@"FROM_APP_TO", @"voice_test"}
                              delegate:self];
```

See, this is how the `params:` parameter works. Twilio service will pass the parameter key-value pairs to your TwiML endpoint and you have the power to dynamically decide the following actions, dial out to another client is just one of the many things you can do with Twilio.

I hope this helps connect the call between your clients.
Please don't hesitate to reach out to us if you have any question and feedback.

cheers,
-bobie

**Comment by nicolettemanas** [comment]
Hi @bchen-twilio 

```
resp = twiml.Response()
resp.dial(callerId='quick_start').client('voice_test')
return resp
```
seems to work but I am now not receiving any voip push notifications to the receiver. 
It was working when we used the `client.calls.create()` method.

Thanks!

**Comment by bchen-twilio** [comment]
Hi @nicolettemanas 

Glad that we made a step forward!
Is this "not-receiving-incoming-push" thing happening 10/10 after you modified the `/placeCall` endpoint or sometimes the push notifications made the way to the callee device?
Other than checking the receiver identity in the access token, you can also go to the [Programmable Voice console](https://www.twilio.com/console/voice/dashboard) and check if there is any error/warning being logged under your account. If there is any push notification related issue, for example Twilio failed to send push due to invalid APNS/VoIP credentials, this is a great place for debugging self-service, in case the team is not able to get back to you in time.

Anyway it would also be great if you could provide us Xcode debug logs (with `.verbose` SDK log-level), as well as the Twilio call-sid (it looks like `CA{32-characters}`). Call-SIDs are incredibly useful for the team to trace down call failures.

cheers,
-bobie

**Comment by nicolettemanas** [comment]
Hi @bchen-twilio 

Sorry, this one's my fault. I switched servers and forgot to change the BUNDLE_ID of the app with a different certificate for voip push notifications. 

Anyway, thanks for the replies! `resp.dial()` is working fine.

**Comment by bchen-twilio** [comment]
Hi @nicolettemanas 

Glad that the solution is helping.
Please feel free to reach out to us if you need any help in the future.
Looking forward to seeing your awesome Twilio applications!

-bobie

**Comment by marecektn** [comment]
I so much thank you for this issue, I've spend whole morning trying to achieve the same behaviour.
So basically when you are calling API with client: prefix, you are using VoIP and when +1234567890 cellular network is used.
Is that correct? (I went through the doc, but Twilio is so damn cool and huge that after 2 days of tutorials I am still on quick sands ;)

**Comment by bchen-twilio** [comment]
Hi @marecektn 

That is not exactly correct. It depends on how the TwiML looks like.
If you the value in the Dial's `callerId` is not prefixed with `client:`, Twilio Voice service will by default take it as a phone number, otherwise `client:XXXX` will be used as the `from` value when the other party receives the call.
For the Programmable Voice mobile SDK, mostly `<Number>` or `<Client>` (plus `<Dial>`) will be used to connect clients or PSTN numbers. As the verb name say, nesting `<Number>` in `<Dial>` will create a call to a phone number. Using `<Client>` will create a call to a registered Twilio client, which will be a "VoIP call" for the receiver client.

Please feel free to create a new issue ticket if you are facing any problem getting your Voice application to work and share the TwiML of the operation you are trying to achieve.
By the way this repository will be closed soon so it'd be great if you could go to the [ObjC quickstart repo](https://github.com/twilio/voice-quickstart-objc) or [Swift quickstart repo](https://github.com/twilio/voice-quickstart-swift) in the future.

Thanks
-bobie
